[server]
port = 8080
debug = true

[database]
host = "localhost"
user = "postgres"
port = 5432
pass = "96320"
name = "taskmanage"
sslmode = "disable"

[jwt]
jwt_secret="$ADBCXVNRETROZNA763546582"


# config.toml
allowed_ips = ["192.168.1.10", "203.0.113.42", "10.0.0.1"]

